#!/usr/bin/env python3
"""Deterministically build board.tsx from the 6 sheets + integration.tsx.

Single source of truth = the sheet .tsx files (+ integration.tsx). This script
strips each sheet's <board> wrapper, renames the cross-sheet refdes collisions,
and concatenates everything into one <board>. board.tsx is GENERATED — never
hand-edit it; edit a sheet (or integration.tsx) and re-run:  python3 merge.py
"""
import re

SHEETS = ["power", "c5-buses", "rf", "audio", "expansion", "indicators"]

# Cross-sheet refdes collisions (only these three names appear in two sheets each).
RENAME = {
    "c5-buses": {"U20": "m_U20"},
    "rf":       {"U20": "rf_U20", "Y1": "rf_Y1", "Rbias": "rf_Rbias"},
    "audio":    {"Y1": "a_Y1", "Rbias": "a_Rbias"},
}


def inner(path):
    """Return the JSX between the opening <board ...> and closing </board>."""
    t = open(path).read()
    m = re.search(r"<board\b[^>]*>", t)
    if not m:
        raise SystemExit(f"{path}: no <board> tag")
    return t[m.end():t.rindex("</board>")].strip("\n")


def rename(txt, mp):
    """Rename a component and every '.name' reference to it (definition + traces)."""
    for a, b in mp.items():
        txt = re.sub(r'name="' + re.escape(a) + r'"', f'name="{b}"', txt)
        txt = re.sub(r"\." + re.escape(a) + r"\b", "." + b, txt)
    return txt


def main():
    blocks = []
    for s in SHEETS:
        body = rename(inner(f"{s}.tsx"), RENAME.get(s, {}))
        blocks.append(f"    {{/* ================= SHEET: {s} ================= */}}\n{body}")
    blocks.append("    {/* ================= INTEGRATION (board-level) ================= */}\n"
                  + inner("integration.tsx"))

    header = (
        "// Leshy2 — MERGED board. GENERATED by merge.py from the 6 sheets + integration.tsx.\n"
        "// DO NOT EDIT BY HAND. Edit a sheet .tsx (or integration.tsx), then run: python3 merge.py\n"
        "// Cross-sheet refdes collisions renamed on merge:\n"
        "//   c5-buses U20 -> m_U20 · rf U20 -> rf_U20 · rf Y1 -> rf_Y1 · audio Y1 -> a_Y1\n"
        "//   rf Rbias -> rf_Rbias · audio Rbias -> a_Rbias\n"
        "// Sheets stitch by shared net.NAME (SPI/I2C/rails/chip-selects/interrupts/C5 link/SP4T select).\n"
    )
    out = (header + "export default () => (\n"
           '  <board width="400mm" height="300mm">\n\n'
           + "\n\n".join(blocks) + "\n\n  </board>\n)\n")
    open("board.tsx", "w").write(out)
    n = len(re.findall(r'name="', out))
    print(f"board.tsx generated: {n} components")


if __name__ == "__main__":
    main()
